// Firebase Auth Actions
export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_ATTEMPT = 'LOGOUT_ATTEMPT';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';

// Websocket Actions
export const CLIENT_CONNECT = 'CLIENT_CONNECT';

// Material UI Actions
export const CHANGE_SIDEBAR = 'CHANGE_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const OPEN_EVENT_DIALOG = 'OPEN_EVENT_DIALOG';
export const CLOSE_EVENT_DIALOG = 'CLOSE_EVENT_DIALOG';
